"""create settings table

Revision ID: d879111a072e
Revises: 
Create Date: 2025-12-29 23:13:09.017556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd879111a072e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_time_et', sa.String(length=5), nullable=False),
    sa.Column('lookback_days', sa.Integer(), nullable=False),
    sa.Column('lookback_type', sa.String(length=16), nullable=False),
    sa.Column('long_threshold', sa.Float(), nullable=False),
    sa.Column('short_threshold', sa.Float(), nullable=False),
    sa.Column('min_price', sa.Float(), nullable=False),
    sa.Column('long_notional_usd', sa.Float(), nullable=False),
    sa.Column('short_qty', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    # ### end Alembic commands ###
